# Generated by Django 3.2.17 on 2023-02-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='created',
            field=models.BooleanField(default=False, verbose_name='created'),
        ),
    ]
